### ISSUE TITLE
[CRASH] RailLogisticsDispatcher::on_nth_tick(2)

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [dvilker/FactorioRailLogisticsDispatcher#12] opened 2022-12-31 08:47 UTC
```
7925.702 Error MainLoop.cpp:1284: Exception at tick 8195410: Мод Rail Logistics Dispatcher (0.0.16) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event RailLogisticsDispatcher::on_nth_tick(2)
Index out of bounds.
stack traceback:
	[C]: in function '__newindex'
	__RailLogisticsDispatcher__/script/TrainClass.lua:428: in function 'gotoToDelivery'
	__RailLogisticsDispatcher__/script/SurClass.lua:178: in function 'correctDeliveriesAtStop'
	__RailLogisticsDispatcher__/script/SurClass.lua:243: in function <__RailLogisticsDispatcher__/script/SurClass.lua:194>
	(...tail calls...)
	__RailLogisticsDispatcher__/script/SurClass.lua:108: in function <__RailLogisticsDispatcher__/script/SurClass.lua:97>
7925.702 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "Мод Rail Logistics Dispatcher (0.0.16) вызвал неустранимую ошибку.
Пожалуйста, сообщите об этой ошибке автору мода.

Error while running event RailLogisticsDispatcher::on_nth_tick(2)
Index out of bounds.
stack traceback:
	[C]: in function '__newindex'
	__RailLogisticsDispatcher__/script/TrainClass.lua:428: in function 'gotoToDelivery'
	__RailLogisticsDispatcher__/script/SurClass.lua:178: in function 'correctDeliveriesAtStop'
	__RailLogisticsDispatcher__/script/SurClass.lua:243: in function <__RailLogisticsDispatcher__/script/SurClass.lua:194>
	(...tail calls...)
	__RailLogisticsDispatcher__/script/SurClass.lua:108: in function <__RailLogisticsDispatcher__/script/SurClass.lua:97>"
```

**Comment by Eldrinn-Elantey** [comment] 2022-12-31 08:58
This happened when using the [Train Upgrader](https://mods.factorio.com/mod/train-upgrader) mod

**Comment by dvilker** [comment] 2023-01-04 09:21
https://github.com/dvilker/FactorioRailLogisticsDispatcher/issues/14

**Comment by dvilker** [comment] 2023-01-04 09:22
This is duplicate of https://github.com/dvilker/FactorioRailLogisticsDispatcher/issues/14

**Closed as not planned** 2023-01-04 09:22 UTC
Labels: duplicate
